filename=prim.cpp
run: $(filename)
	g++ -std=c++11 -o a.out $(filename) && \
	./a.out ../input_0.csv > ../solution_yours_0.csv && \
	./a.out ../input_1.csv > ../solution_yours_1.csv && \
	./a.out ../input_2.csv > ../solution_yours_2.csv && \
	./a.out ../input_3.csv > ../solution_yours_3.csv && \
	./a.out ../input_4.csv > ../solution_yours_4.csv && \
	./a.out ../input_5.csv > ../solution_yours_5.csv && \
	./a.out ../input_6.csv > ../solution_yours_6.csv 

test: $(filename)
	g++ -std=c++11 -o a.out $(filename) && \
	./a.out ../input_0.csv 
	./a.out ../input_1.csv 
	./a.out ../input_2.csv 
	./a.out ../input_3.csv 
	./a.out ../input_4.csv 
	./a.out ../input_5.csv 
	./a.out ../input_6.csv 

test2: $(filename)
	g++ -std=c++11 -o a.out $(filename) && \
	./a.out ../input_2.csv 

test3: $(filename)
	g++ -std=c++11 -o a.out $(filename) && \
	./a.out ../input_3.csv 

test4: $(filename)
	g++ -std=c++11 -o a.out $(filename) && \
	./a.out ../input_4.csv 

test5: $(filename)
	g++ -std=c++11 -o a.out $(filename) && \
	./a.out ../input_5.csv 

test6: $(filename)
	g++ -std=c++11 -o a.out $(filename) && \
	./a.out ../input_6.csv 
